[project]
name = 'Pharmaceutical-Supply-Chain-Tracking-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.batch-tracking]
path = 'contracts/batch-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.manufacturer-registration]
path = 'contracts/manufacturer-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
